### ISSUE TITLE
log4j Dependency issue

### ISSUE THREAD

**Issue by emalkan** [Azure-Samples/azure-cosmos-db-graph-java-getting-started#10]
I am trying to use this code as a baseline for connecting my Scala App to Cosmos DB. However I keep getting this issue -
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

On searching online, I tried solutions [here](https://stackoverflow.com/questions/12532339/no-appenders-could-be-found-for-loggerlog4j) and [here](https://stackoverflow.com/questions/38360874/the-import-org-apache-log4j-cannot-be-resolved). However nothing seems to work. 
Can you help me with this issue, or provide a scala connector guide for Cosmos DB with gremlin.

Thanks a lot!

**Comment by olivertowers** [comment]
Closing as not relevant - This is a general log4j/java issue and not specific to CosmosDB/Gremlin
