### ISSUE TITLE
Result.getVertex() fails with "java.util.LinkedHashMap cannot be cast to org.apache.tinkerpop.gremlin.structure.Vertex"

### ISSUE THREAD

**Issue by steveardis** [Azure-Samples/azure-cosmos-db-graph-java-getting-started#12]
See: https://github.com/steveardis/azure-cosmos-db-graph-java-getting-started/commit/7a0db8dae366b4d5403b912bde9be612a239e536

**Comment by steveardis** [comment]
I think I understand this now.  Am I unable to use Result.getVertex() because Cosmos DB only supports GraphSON.  Said differently, will Result.getVertex() only work with the Gryo serializer and is thus not support because Cosmos DB only support GraphSON?

**Comment by LuisBosquez** [comment]
@steveardis I believe this is the case at the moment. We have added this item to the backlog and will update this thread

**Comment by karthik1289** [comment]
@LuisBosquez Is it not fixed still?

**Comment by olivertowers** [comment]
This is the current behavior today.
