### ISSUE TITLE
How do I actually traverse through the edges?

### ISSUE THREAD

**Issue by rajanpupa** [Azure-Samples/azure-cosmos-db-graph-java-getting-started#15]
I am trying the microsoft gremlin db example in azure and I could not find any example where I could actually traverse through the certain edges of a Vertex and find other vertex. Can someone please point me to the right direction?

**Comment by olivertowers** [comment]
You can use out() is a traversal steps that you can use to traverse to neighbor vertices along edges, eg:
`g.V('<vertex_id>').out('<edge_label>')`

This says, find all neighbors to <vertex_id> along out-edges with label <edge_label>

If you are interesting in applying more specific filters on edges, you can use outE() step with has() to filter on edge properties, and then use inV() to hop to the neighbor vertex. eg:
`g.V('<vertex_id>').outE('<edge_label>').has('<edge_property_key>', '<edge_property_value>').inV()`

This says, find all neighbors of <vertex_id> along out-edges with label <edge_label> and <edge_property_key> = <edge_property_value>

Recommended reading for learning gremlin. Note, these are not specific to Cosmos DB Gremlin and use the open source TinkerGraph gremlin engine. 
- [Getting started with gremlin](http://tinkerpop.apache.org/docs/3.4.2/tutorials/getting-started/)
- [Gremlin reference guide](http://tinkerpop.apache.org/docs/current/reference/#graph-traversal-steps)

**Comment by olivertowers** [comment]
Closing issue - answer provided.
