### ISSUE TITLE
Maven build failure

### ISSUE THREAD

**Issue by gorankuk** [Azure-Samples/azure-cosmos-db-graph-java-getting-started#16]
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target ->

**Comment by olivertowers** [comment]
Issue no longer repros - closing.
