### ISSUE TITLE
Can we create one new database with collection name from gremlin cluster/client?

### ISSUE THREAD

**Issue by Incarnation-p-lee** [Azure-Samples/azure-cosmos-db-graph-java-getting-started#9]
It seems we can only connected to one existed endpoint for gremlin side, And cannot create one new database of cosmosdb, and specify collection names, right?
Could you please help to confirm this ?
Thanks a lot.

**Comment by LuisBosquez** [comment]
Hello @Incarnation-p-lee, to create new databases and collections you have to use the Cosmos DB Java SDK: https://docs.microsoft.com/en-us/azure/cosmos-db/create-sql-api-java This provides that functionality.
